/* Generated By:JavaCC: Do not edit this line. MaplParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MaplParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 8;
  /** RegularExpression Id. */
  int LPAREN = 9;
  /** RegularExpression Id. */
  int RPAREN = 10;
  /** RegularExpression Id. */
  int PROC = 11;
  /** RegularExpression Id. */
  int FUN = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int TRUE = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int NOT = 16;
  /** RegularExpression Id. */
  int LSQBR = 17;
  /** RegularExpression Id. */
  int RSQBR = 18;
  /** RegularExpression Id. */
  int LBRACE = 19;
  /** RegularExpression Id. */
  int RBRACE = 20;
  /** RegularExpression Id. */
  int SEMICOLON = 21;
  /** RegularExpression Id. */
  int ASSIGN = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int LESSTHAN = 24;
  /** RegularExpression Id. */
  int EQUALS = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int PLUS = 27;
  /** RegularExpression Id. */
  int MINUS = 28;
  /** RegularExpression Id. */
  int TIMES = 29;
  /** RegularExpression Id. */
  int DOT = 30;
  /** RegularExpression Id. */
  int ISNULL = 31;
  /** RegularExpression Id. */
  int LENGTH = 32;
  /** RegularExpression Id. */
  int COMMA = 33;
  /** RegularExpression Id. */
  int BOOLEAN = 34;
  /** RegularExpression Id. */
  int ARRAYOF = 35;
  /** RegularExpression Id. */
  int NEW = 36;
  /** RegularExpression Id. */
  int ELSE = 37;
  /** RegularExpression Id. */
  int THEN = 38;
  /** RegularExpression Id. */
  int IF = 39;
  /** RegularExpression Id. */
  int WHILE = 40;
  /** RegularExpression Id. */
  int DO = 41;
  /** RegularExpression Id. */
  int OUTPUT = 42;
  /** RegularExpression Id. */
  int OUTCHAR = 43;
  /** RegularExpression Id. */
  int RETURN = 44;
  /** RegularExpression Id. */
  int ID = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<INTEGER_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"proc\"",
    "\"fun\"",
    "\"int\"",
    "\"true\"",
    "\"false\"",
    "\"!\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"and\"",
    "\"<\"",
    "\"==\"",
    "\"div\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".\"",
    "\"isnull\"",
    "\"length\"",
    "\",\"",
    "\"boolean\"",
    "\"arrayof\"",
    "\"new\"",
    "\"else\"",
    "\"then\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"output\"",
    "\"outchar\"",
    "\"return\"",
    "<ID>",
  };

}
